### PR TITLE
Wider icon  headings in 2-wide grid

### PR DESCRIPTION
**Pull request by noahmanger**
Makes the `icon-heading__image` wider when in a two-column layout, such as:

example

### CODE REVIEW

**Comment by jenniferthibault** [comment]
Sorry to chime in untagged, but want to flag that I may have not communicated the design specs/intention well after adding the larger images.

The larger images (136 px ) are intended for the commissioner bio page templates.

On index views (this page, the home page, and the all commissioners page) the images should stay small scale (previously ~86px).

Am I reading this wrong @noahmanger ?

**Comment by noahmanger** [comment]
Oh! Gotcha. I'll adjust.

**Comment by xtine** [comment]
@jenniferthibault: Adjusted icon sizes:
screencapture-127-0-0-1-8000-about-leadership-and-structure-1485468295201

**Comment by xtine** [comment]
I had to fix some template logic because the commissioners werent showing properly in the Commissioner Block, so before merging make sure https://github.com/18F/fec-cms/pull/765 is also merged in.

**Comment by jenniferthibault** [comment]
Thank you @xtine !

**Pull request merged**
