### PR TITLE
Updating styleguide

### LINKED ISSUE #195: Add color section to style guide
I think this would help us keep track of the colors we're using, what they're named, and the hex codes.

MVP would be a color block with the hex code and name.
Phase 2 might include color combinations and their color contrast relationships.

### PR DESCRIPTION
**Pull request by noahmanger**
Adds the color page to the styleguide.

Resolves #195

### CODE REVIEW

**Comment by noahmanger** [comment]
@jenniferthibault if this color page looks good to you we can merge this:

screen shot 2016-02-19 at 3 12 53 pm

**Comment by jenniferthibault** [comment]
On the light colors, it would be nice to have a dark text so that you can see the hex value, but keep the light text on other colors. Goal, essentially: be able to read the text of the hex value, so we need a light and a dark.

Current:
screen shot 2016-02-25 at 12 04 37 pm

Ideal:
screen shot 2016-02-25 at 12 02 01 pm

I poked around to figure out if I could do it, but got confused by the kss

Other than that :+1:

**Comment by noahmanger** [comment]
Good lookin' out! Got it.

**Comment by jenniferthibault** [comment]
Nice! Cool fix. Looks good to me.

**Pull request merged**
