### PR TITLE
Adding list/calendar toggle buttons and styles

### PR DESCRIPTION
**Pull request by noahmanger**
Styles for the pending calendar list / grid view toggles.

### CODE REVIEW

**Comment by noahmanger** [comment]
@jenniferthibault I forgot to follow up on this, but can you send me whichever icons you want to use for the grid/list toggles when you have a chance?

**Comment by jenniferthibault** [comment]
Added!

**Comment by noahmanger** [comment]
Thanks! Ok, ready for review.

**Comment by jmcarp** [comment]
Minor, but I think the color indicator looks a little off for the rulemaking category:

screen shot 2016-03-14 at 1 32 28 pm

**Comment by noahmanger** [comment]
Hm I don't see that:

screen shot 2016-03-14 at 12 02 21 pm

At any rate, this code doesn't touch that, so not sure what's up.

**Comment by jmcarp** [comment]
Still need to release fec-style to npm and patch the other release branch(es) for this to be included in the release.

**Pull request merged**
