### PR TITLE
New alert styles

### PR DESCRIPTION
**Pull request by noahmanger**
## Summary
- Updates some styles for messages based on https://github.com/18F/fec-style/issues/266
- Removes some declared `color` properties in favor of more inheritance. This might break some things, so need to look through carefully
- Adjusts the feedback template so that the "File a new issue" and "Track your issue" buttons are aligned

## Screenshots
image

image

### CODE REVIEW

**Comment by jenniferthibault** [comment]
Taking a look at this and it's partner https://github.com/18F/openFEC-web-app/pull/1205
now.

**Comment by jenniferthibault** [comment]
To do/discuss:

- Add space between the buttons in the feedback form success screen and the No results pattern: they are pretty tight and could easily be confused for a toggle
screen shot 2016-04-28 at 11 08 46 am

screen shot 2016-04-28 at 11 23 32 am

I also think that we want to put the `File an issue` button BEFORE the `Email our team` option in all scenarios. Do we want to pick which is the call to action here?

- Call to action button is a different size than the alt-style buttons on the 504/404 pages:
screen shot 2016-04-28 at 11 05 14 am

**Comment by noahmanger** [comment]
Good 👀 . Added that spacing and fixed the height differences.

image

image

**Comment by noahmanger** [comment]
I'm confused by what's failing with Codecov. @adborden ?

**Comment by adborden** [comment]
Codecov looks okay to me, what do you see that's failing?

**Comment by noahmanger** [comment]
Ah nice. It was failing earlier and I couldn't tell why.

On Wed, May 11, 2016 at 5:02 PM, Aaron D Borden <notifications@github.com>
wrote:

> Codecov looks okay to me, what do you see that's failing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/pull/337#issuecomment-218624975>
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by ccostino** [comment]
Looks like this is good to go now from my end after testing, thank you!

**Pull request merged**
