### PR TITLE
Clarifying style guide

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary

[Don't merge yet] 
This was my first attempt at #281 and #283 , but I didn't get very far. I either wasn't editing the right kss elements, or the files weren't updating on my local version. Can't tell and it was taking wayyyy too long to fight that fight. I'm going to leave the branch here for @noahmanger to work off of, and work with Sketch mockups in the issues from here.

### CODE REVIEW

**Comment by noahmanger** [comment]
Ok! Just made a bunch of changes based on your styles:

image

There's definitely more that can be done to refine it, but I think it's pretty good for now.

**Comment by jenniferthibault** [comment]
I made a few small tweaks (lightened the sidebar color, and made Draft all uppercase).

One final change that I think would be helpful at this stage, but I didn't add on my own, is to add in a link hover style to the items in the navigation—either adding a dotted underline on hover or changing the text color ($federal-blue: #112E51) so that there's a visual cue when you hover.

With that one last change 👍

**Comment by jenniferthibault** [comment]
@emileighoutlaw we put this copy on the home page together to let people know that the style guide is a work in progress, since it's now public facing. 

Your thoughts or revisions are very welcome if you have them!

**Comment by emileighoutlaw** [comment]
Taking a look!

**Comment by emileighoutlaw** [comment]
Q: Is it true that people _won't_ find complete documentation or a full list of design patterns? If so, I think we should say "you won't" rather than "you may not."

Otherwise, I made one small content commit, and I think this looks great!

**Comment by jenniferthibault** [comment]
It is true, they *will not*....yet!  How about 
>... you won't find a full list of design patterns or complete documentation behind what's here quiet yet. We are developing these resources as we build the site.

Idk, that sounds kind of curt, and I'm not sure what the right tone is, but gets to the idea!

**Comment by noahmanger** [comment]
Thanks all! Just added the hover state. @jenniferthibault if it looks good to you, do you want to merge?

**Comment by jenniferthibault** [comment]
HECK YES I DO

**Comment by adborden** [comment]
Sorry I'm late to the party, @noahmanger: for the sidebar, maybe you want `overflow-y: scroll`? Right now we get both horizontal and vertical scrollbars. Here's a screenshot from Ubuntu Chrome:

screenshot from 2016-04-18 15-46-39

**Pull request merged**
