### PR TITLE
Calendar list styling

### PR DESCRIPTION
**Pull request by jenniferthibault**
(in progress)

### CODE REVIEW

**Comment by noahmanger** [comment]
Should we close #213 in favor of this?

**Comment by noahmanger** [comment]
Or looks like #213 is further ahead?

**Comment by jenniferthibault** [comment]
To be honest, my commits and branches and patches around this were made in a state similar to a blindfolded toddler aiming for a piñata, and accidentally hitting a bystander. Yeah, you've all seen the videos of how that works. @jmcarp did a lot of manual merges, and probably has the best idea.

**Comment by jmcarp** [comment]
Yep, all of @jenniferthibault's commits here have been merged into `styling-calendar`. Closing.

**Pull request closed without merging**
