### PR TITLE
Restore dropdown and update unit tests.

### PR DESCRIPTION
**Pull request by jmcarp**
Please check out and verify that this is working as expected @noahmanger.

### CODE REVIEW

**Comment by msecret** [comment]
This looks good to me, will wait for @noahmanger to check.

**Comment by noahmanger** [comment]
Working well. We do need to make this work with tabbing though at some point. Could do it now or later.

**Comment by jmcarp** [comment]
In the interest of demos working right away, we should probably merge. @noahmanger can you describe the desired tabbing behavior? I'll get to that next.

**Comment by noahmanger** [comment]
When the parent `<li>` has focus, the submenu should be revealed, and then you should be able to tab through it.

**Pull request merged**
