### PR TITLE
Updates licensing and attribution information

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary

- Clarifies that not all work is public domain by specifying font licenses
- Provides specific licenses for fonts
- Provides basic guidance on image licenses

This update is well-overdue, I mistakenly thought it was already in here 😲 
Thanks to @patphongs for asking the good questions!

### CODE REVIEW

**Comment by noahmanger** [comment]
Should somebody more versed in this review? I really don't know what to look for here.

**Comment by jenniferthibault** [comment]
I was wondering some of the same—who do you think should review?

**Comment by jenniferthibault** [comment]
@brittag of #wg-opensource has generously offered to take a look!

**Comment by jenniferthibault** [comment]
@brittag brought up a few great points of feedback:
- > For "This site is based on the U.S. Web Design Standards (WDS)", can you be more specific about which bits of this repository are based on which bits from there? Something like "This repository includes files forked from the U.S. Web Design Standards (WDS)" ?
I ask because that can help people identify which bits are under which license

After looking around I couldn't find exactly any places where we'd forked the USWDS code or assets. To address this, I removed the clause about USWDS-specific licenses from `LICENSE.md` (since we specifically aren't integrating any of their fonts that fall under those licenses) and added a more general design and guidance attribution below.

- > This says "As stated in [CONTRIBUTING](CONTRIBUTING.md), all contributions to this project will be released under the CC0 dedication." in the LICENSE file, but it looks like https://github.com/18F/fec-style/blob/master/CONTRIBUTING.md says "By submitting a pull request, you agree to comply with the policies on our LICENSE page." which is a bit circular

She recommended we use the boilerplate from https://github.com/18F/open-source-policy/blob/master/CONTRIBUTING.md , which I placed in `CONTRIBUTING.md` and made sure all references to more contributing info pointed only to the `CONTRIBUTING.md file. "All contributions to this project will be released under the CC0 dedication. By submitting a pull request, you are agreeing to comply with this waiver of copyright interest."


@noahmanger as the person who set this repo up, if you know of code or assets we forked from USWDS that I didn't find, please point me to them!

**Comment by noahmanger** [comment]
The only tiny bit of code I can think of that was taken from WDS was these utility classes for grids: https://github.com/18F/fec-style/blob/master/scss/_grid.scss#L12

Not sure if that's worth a specific call-out or not. It was basically just copy and paste from an example file.

**Comment by jenniferthibault** [comment]
Great! That made me realize we could list the selection of elements as we know of them. Seems like it's best to nod to the inspiration, even when we digressed. Just added a change to list the items that I knew of, but I'm not sure if I formatted the relative links correctly, so would appreciate a check on that.

screen shot 2017-03-22 at 12 37 30 am

screen shot 2017-03-22 at 12 38 20 am

**Pull request merged**
