### PR TITLE
Styles for the widgets on the data home

### PR DESCRIPTION
**Pull request by noahmanger**
Adds the styles for the election widgets on the data landing page:

screen shot 2015-09-08 at 8 13 31 pm

### CODE REVIEW

**Comment by jmcarp** [comment]
This is very minor, but would be nice to fix: the district dropdown and search button aren't exactly aligned:
screen shot 2015-09-09 at 10 18 02 am
#hairsplitting

**Comment by noahmanger** [comment]
Good eye! I noticed that too but was having trouble figuring out what
exactly the issue was.

On Wed, Sep 9, 2015 at 7:20 AM, Joshua Carp <notifications@github.com>
wrote:

> This is very minor, but would be nice to fix: the district dropdown and
> search button aren't exactly aligned:
> [image: screen shot 2015-09-09 at 10 18 02 am]
> <https://cloud.githubusercontent.com/assets/1633460/9764268/3342b2a4-56dc-11e5-91be-66adcf00709e.png>
> #hairsplitting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/pull/74#issuecomment-138924586>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
I see where this started! Not in the code, but in the design. When users started asking for a button to implement or apply search queries/filters, I added a word/icon action button, like so, which is separate from the data fields. Is it possible to make it match this? 
screen shot 2015-09-09 at 12 53 19 pm

**Comment by jenniferthibault** [comment]
Rather, this: sorry.
screen shot 2015-09-09 at 1 21 25 pm

**Comment by noahmanger** [comment]
Is there a reason you don't want the button in line with the fields? It
looks a little weird to me offset, but your call.

On Wed, Sep 9, 2015 at 10:22 AM, Jennifer Thibault <notifications@github.com
> wrote:

> Rather, this: sorry.
> [image: screen shot 2015-09-09 at 1 21 25 pm]
> <https://cloud.githubusercontent.com/assets/11636908/9769066/bd1e5b9a-56f5-11e5-8bee-c01cfcbd4a8c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/fec-style/pull/74#issuecomment-138982407>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by jenniferthibault** [comment]
My hunch was that  the user's mouse would already be close to the ahead where I put the search button, so it would make a quick transition to click, rather than going back to the beginning of the line.

I'm all for keeping to the grid though, so I'm sure it wouldn't be an obstacle! Let's put it in line!

**Comment by noahmanger** [comment]
Ok, aligned the buttons. Should be good to go.

**Comment by jmcarp** [comment]
LGTM

**Pull request merged**
