### PR TITLE
Advanced data styles

### PR DESCRIPTION
**Pull request by noahmanger**
## Summary

- Adds small styles for advanced data index:
  - Style for nested lists
  - Style for `list--spacious` which provides more padding
  - Style for links to tables that contain all of a given data set
- Moves the table of contents component from fec-cms to here (same code, doesn't need a review)
- Adds new `card__icon` class for using CSS background images for card icons

## Screenshots
image
image
image

image

### CODE REVIEW

**Comment by noahmanger** [comment]
Ready for review.

**Comment by adborden** [comment]
Looks good, don't forget to wrap those `rem`s with `u()` ;)

I'll take care of it this time.

**Comment by jenniferthibault** [comment]
Whoopsie—I just caught one style adjustment I'd like to make to `h1` borders now that we aren't using display. I'll file that separately!

**Comment by adborden** [comment]
Aw, sorry, I was too quick.

--
Aaron D Borden
Human and Hacker

**Comment by jenniferthibault** [comment]
More likely, I was too slow!

**Pull request merged**
