### PR TITLE
orange document icon for homepage

### PR DESCRIPTION
**Pull request by xtine**
Makes an orange specific icon for homepage secondary card.

screen shot 2017-03-22 at 5 51 05 pm

Supports https://github.com/18F/fec-cms/pull/903

### CODE REVIEW

**Comment by jenniferthibault** [comment]
This is the same icon from https://github.com/18F/fec-cms/pull/885/files#diff-b5fca762a031c4182e25a1859f97e9c2R31

Does that mean it's already in the repo? Or it is, but this is still needed?

**Comment by jenniferthibault** [comment]
Maybe this is the more relevant one, but it wasn't filed until just now: https://github.com/18F/fec-style/pull/651

**Comment by xtine** [comment]
@jenniferthibault: the document icon is in the repo, but default color is black. This just sets the styling for the orange version.

**Comment by jenniferthibault** [comment]
😳 Ohh I see now that it was referencing the cards file, not the icons file. Thanks for translating!

**Comment by noahmanger** [comment]
Is it just me or is the sizing a little off? I tried it at `background-size: 50%` and think it looks better:

image

**Comment by xtine** [comment]
@noahmanger: thanks for the suggestion, it does look better and more uniform with the other card icons now.

**Comment by noahmanger** [comment]
@jenniferthibault this look right?

**Comment by jenniferthibault** [comment]
Yes! the 50% size is right on the money 💸

**Pull request merged**
