### PR TITLE
Printer styles

### PR DESCRIPTION
**Pull request by noahmanger**
## Summary
This fixes various issues with broken print styles by:
- Adding `@media print` media queries in partials that need explicit definition to show or hide things on print
- Adds various styles to reset elements with dark backgrounds (`.card`, `.slab`, `.hero`) to be white background with dark text
- Adding a new `print-logo.png` asset, which must be loaded as an `img` in the header, rather than as a `background-image` in order to be rendered on certain browsers
- Adding a `.u-print-only` utility class that hides an element on screens and shows it on print
- Refactors the media queries in the `_site-header.scss` and `_breadcrumbs.scss` partials in order for more styles to naturally be applied on print

## Screenshots
image

cc @jenniferthibault @xtine 

@jenniferthibault : The SVG you sent along was really large and also had parts that I didn't actually need. I took a stab at doing just a logo + wordmark combo and added it as a .png. Does this work for you?

Resolves https://github.com/18F/fec-cms/issues/446

Requires upcoming PRs to web-app and cms to add the printer logo.

### CODE REVIEW

**Comment by emileighoutlaw** [comment]
Wooo! Yay @noahmanger 🎉 🎉 🎉

**Comment by jenniferthibault** [comment]
@noahmanger sorry, miscommunication when I sent you the option with and without text earlier, but I don't know why it was huge....it was made from a letter-sized page.


The spacing around the wordmark and seal are a tricky balance—the factor that makes them work is the incomplete grey line on the upper left, which lets the seal be a little bit bigger, while keeping the text small. I see why using an image of them locked together seems like the most accurate way to get it matching.

Try this one?

[Header-print Copy.svg.zip](https://github.com/18F/fec-style/files/452940/Header-print.Copy.svg.zip)

**Comment by noahmanger** [comment]
Got it. Thanks!

**Comment by noahmanger** [comment]
@adborden do you have time to give this a look today?

**Pull request merged**
