### PR TITLE
Version using semver.

### PR DESCRIPTION
**Pull request by jmcarp**
Proposal: Version fec-style using semantic versioning. Bug fixes
increment the patch, non-breaking changes increment the minor version, and
breaking changes increment the major version. To support flexible
version ranges (e.g. ~1.0.0), fec-style should be published to npm. If
we go in this direction, everyone who needs to be able to push changes
will need an npm account with permissions to update the fec-style
package. I'm arbitrarily calling this version 1.0.0.

Thoughts @noahmanger @shawnbot @msecret? I'm also hoping that versioning upstream dependencies gets simpler as we break more components out of fec-style and into their own packages.

### CODE REVIEW

**Comment by noahmanger** [comment]
Nice. I'm into this. The only question I have now is how to categorize Sass changes? I might need to see some examples around what counts as a breaking change vs. non-breaking, considering the possibility of unintended side effects.

**Comment by jmcarp** [comment]
Some breaking changes will be obvious--if we change classes or DOM structure such that consumers will have to change their markup, we definitely have breaking changes. But yeah, I can see how it could be hard to tell whether a style change here would break things downstream. In practice, I think we'll want to continue manually testing all changes to fec-style against a local version of openFEC-web-app, which would hopefully help us catch unexpected side effects.

This may also be a good issue to bring up in #g-frontend.

**Comment by noahmanger** [comment]
Can you resolve the conflicts? And then I'll merege.

**Comment by jmcarp** [comment]
Conflicts resolved.

Related to this: to make it safe to merge breaking changes into master, I think we should hotfix the data site and CMS to pin to the current commit; then merge in pending (potentially breaking) changes; then release to npm. Then we'll install from npm and pin to the appropriate (fuzzy) version going forward. Thoughts?

**Comment by noahmanger** [comment]
That sounds good with the one exception that we should do a thorough review to make sure we haven't accidentally introduced breaking changes since production was last deployed.

**Pull request merged**
