### PR TITLE
Unique tooltip

### PR DESCRIPTION
**Pull request by noahmanger**
Adds styles for tooltips underneath content (with the arrow above).

### CODE REVIEW

**Comment by jmcarp** [comment]
One minor issue here: after checking the "unique only" checkbox, the associated tooltip stays on the screen until the user clicks somewhere else. If the user doesn't know they have to change focus, the filter element underneath can be obscured. I'm going to merge this now, but we might want to roll back the rule that shows tooltips on trigger focus @noahmanger.

**Comment by noahmanger** [comment]
Good catch. We need it to be visible on focus somehow for keyboard accessibility. But maybe the way to do it is to have an icon and if you focus or hover on _that_ then it shows.

**Comment by jmcarp** [comment]
SGTM! Do you have time to look at this soon, or should we file an issue for the backlog?

**Comment by noahmanger** [comment]
Just added a note to this issue to make sure we address it: https://github.com/18F/openFEC-web-app/issues/689

**Pull request merged**
